WIP update to use InterTypes
AlgebraicJulia/SyntacticModels.jl pull request #29
Opened 2023-12-01 15:34 UTC by p-stokes

This is to make the InterType form of the various structures currently in SyntacticModels.

Resolves #28

2023-12-06 16:51 UTC, jpfairbanks requested changes
The unnecessary rename of these file makes the diffs unreviewable. Please put them back and confirm that the diffs are useful. I can review again at that time.

2023-12-06 16:51 UTC, jpfairbanks commented on Project.toml
> +Decapodes = "0.4, 0.5"
Since code is moved here, do we still need to depend on Decapodes?

2023-12-06 16:51 UTC, jpfairbanks commented on src/amr_it.jl
> +module AMR
because of the rename of this file, the diff is useless. See above comment.

2023-12-06 16:51 UTC, jpfairbanks commented on src/amr_it.jl
> +# using ..SyntacticModelsBase
Delete commented out code

2023-12-06 16:51 UTC, jpfairbanks commented on src/amr_it.jl
> +#=
delete block comments.

2023-12-06 16:51 UTC, jpfairbanks commented on src/amr_it.jl
> +#=
why isn't this being used?

2023-12-06 16:51 UTC, jpfairbanks commented on src/composite_models_it.jl
> +module Composites
again, I can't review this diff because of the file rename.

2023-12-06 16:51 UTC, jpfairbanks commented on src/decapodes_it.jl
> +# using Decapodes
is anything using Decapodes now that you copied code over here? Should we upgrade Decapodes to use InterTypes and then just use InterType inteheritance here?

2023-12-06 16:51 UTC, jpfairbanks commented on src/decapodes_it.jl
> +function recognize_types(d::decapodes.AbstractNamedDecapode)
Should SynacticModels be doing decapodes operations like `recognize_types`? What do you think the scope boundary is?

2023-12-06 16:51 UTC, jpfairbanks commented on src/decapodes_it.jl
> +function parse_decapode(expr::Expr)
Should SynacticModels be doing decapodes operations like `parse_decapode`? What do you think the scope boundary is?

2023-12-06 16:51 UTC, jpfairbanks commented on src/uwd_it.jl
> +module ASKEMUWDs
I can't review this diff because the file was renamed unnecessarily.

2023-12-07 02:43 UTC, p-stokes commented
> The unnecessary rename of these file makes the diffs unreviewable. Please put them back and confirm that the diffs are useful. I can review again at that time.

I've updated the file names for the PR, and the diffs look ok now. Regarding the included decapodes functions, I think the longer-term plan is for Decapodes and other structures to be defined directly upstream with InterTypes. But for the short-term, it seemed easier to develop locally within SyntacticModels.

I do think it would be helpful to have a discussion about the design/scope plan for SyntacticModels because it relates to the current points of development for the AMR and Composites functionality as well.

2023-12-07 02:45 UTC, p-stokes commented on src/SyntacticModels.jl
> +include("amr_it.jl")
It was just for development purposed. I've renamed them.

2023-12-07 18:01 UTC, p-stokes commented on test/composite_models_examples.jl
> +h = Header("","harmonic_oscillator",
In the Model-Representations repo, I noticed Five had added an extra `id` field to the `Header` there, so I incorporated it here. I can go through and take it out if you want?

2023-12-07 18:13 UTC, p-stokes commented on test/composite_models_examples.jl
> +import JSON3
Similar to the name qualifications, I was a bit lax with the imports during development. 
I have already begun going through and cleaning up some of the unnecessary imports.

2023-12-08 07:00 UTC, p-stokes commented
I cleaned up and standardized the imports and name qualifications. Still working on the remaining composite `oapply` example and amr `acsetspec` examples

2023-12-08 07:02 UTC, p-stokes commented on src/composite_models.jl
> +using Decapodes # : SummationDecapode
It was deleted in the imports cleanup.

2023-12-08 14:16 UTC, jpfairbanks commented on src/amr.it
> +#=
do we need this?

2023-12-08 14:16 UTC, p-stokes commented on test/composite_models_examples.jl
> +h = Header("","harmonic_oscillator",
Ok. I'll undo that and make a separate issue and PR after.

2023-12-08 14:19 UTC, jpfairbanks commented on src/amr.it
> +@sum Args begin
Is this being copied from https://github.com/AlgebraicJulia/ACSets.jl/blob/main/src/ADTs.jl#L14?

We should upgrade that code to use InterTypes and then import that usage here.

2023-12-08 16:28 UTC, p-stokes commented
> > I do think it would be helpful to have a discussion about the design/scope plan for SyntacticModels because it relates to the current points of development for the AMR and Composites functionality as well.
> 
> I think the first part of that discussion is understanding your expectations for the scope. What are your thoughts?

Summarizing our in-person discussion about this: 
The short-term scope is to convert the functionality and test examples to use `InterTypes` locally within SyntacticModels.jl (as best makes sense and is possible). Longer-term, the .it files and functions will be upstreamed to their respective repositories.
There are several blocking issues with `InterTypes`' capabilities and integration with some other upstream functionality (e.g., `ADTs` and `Open`). I will make issues for those and tag them below.

2024-01-17 21:00 UTC, closed without merging

2024-01-17 21:01 UTC, olynch commented
Some of the work here ends up duplicating work merged into DiagrammaticEquations, so it makes sense to make a new PR